export {default as Header} from './Header/Header'
export {default as Main} from './Main/Main'
export {default as Elemntor} from './Elemntor/Elemntor'
export {default as Best_product} from './Best_product/Best_product'
export {default as Shop_now} from './Shop_now/Shop_now'
export {default as Sell} from './Sell/Sell'
export {default as Reviews} from './Reviews/Reviews'
export {default as Logos} from'./Logos/Logos'
export {default as Shop} from './Shop/Shop'
export {default as Footer} from './Footer/Footer'